---
title: "Research Proposal: The Role of Transparency in the fight against Political Corruption in Europe "
author: Mariam Sanjush and Roberto Martinez B. Kukutschka
output: pdf_document
bibliography: bibliography.bib
---


# Introduction
Corruption has not always been perceived as something negative. Until today the debate of whether corruption greases or sands the wheels of economic growth still lingers [@bardhan1997; @pande2008; @aidt2009]. Those in favour of the greasing hypothesis argue that corruption facilitates trade that may not have happened otherwise and promotes efficiency by allowing private sector agents to overcome cumbersome regulations [@leff1964; @huntington1968; @meon2010]. Opponents of this view, meanwhile, have built a solid theoretical rebuttal by arguing that the greasing effect of corruption is only possible as a second best option in a bad institutional setting.  

Since the mid-1990s, when Transparency International (TI) and the World Bank (WB) popularized their measurements of corruption, the damaging effects of this phenomenon have been widely documented in the academic literature. Mauro [@mauro1995] argues that corruption reduces investment across developing countries, thereby negatively affecting growth. Reinikka and Svensson [@reinikka2005] find that corruption has detrimental effects on human capital accumulation. There are also studies showing that corruption directly affects the structure of public budgets by directing more resources to sectors with a higher degree of discretionality, often at the expense of the provision of public goods such as healthcare and education [@tanzi1998].  

Corruption is often thought as a problem of the developing world and there are indeed a plethora of academic studies documenting the links between corruption and different measurements of development Corruption continues to be a challenge for Europe - a phenomenon that costs the European economy around 120 billion euros per year [@eu2014]. Moreover, the Eurobarometer survey results show that three quarters (76%) of Europeans think that corruption is widespread and more than half (56%) think that the level of corruption in their country has increased over the past three years. These numbers contrast sharply with the number of Europeans reporting to having been asked to pay a bribe in the past 12 months (6%).  

What explains this gap, between lack of experience of corruption and high perceptions of it in the EU28? Before answering this question it is important to draw the difference between different types of corruption, i.e. petty or bureaucratic corruption and grand or political corruption. The former is mostly understood as the abuse of entrusted power by public officials in their interactions with ordinary citizens, who often are trying to access basic goods or services in places like hospitals, schools, police departments and other agencies. This type of corruption is often considered to be the most visible one, as citizens have to experience it directly. The latter, often more damaging type of corruption, refers to the abuse of high-level power that benefits the few at the expense of the many, and causes serious and widespread harm to individuals and society through the manipulation of policies, institutions and rules of procedure in the allocation of resources and financing by political decision makers, who abuse their position to sustain their power, status and wealth.  

Evidence from recent surveys shows that the explanation might reside in the widespread belief that grand or political corruption is widespread in the continent and that the political and economic elites are profiting from undue advantages (Mungiu-Pippidi 2014). Evidence from the 2013 Quality of Government survey conducted by the University of Gothenburg and the European Commission???s Special Eurobarometer 79 shows that citizens all over Europe, including the advanced democracies of Western and Northern Europe, have come to believe that success in the public sector is determined by networks rather than by hard work and that these political connections are essential to succeed in the business world as well.  

Most studies dealing with political corruption focus on authoritarian regimes because under such regimes corruption is simply the form of government and the mechanism through which the ruler manages the economy. However, as demonstrated by a large number of corruption scandals in liberal democracies over the years, political corruption is not restricted to authoritarian systems. Political corruption has even been cited as an important driver of the global and the European Financial crises.  

Due to its corroding effects on state institutions, high social and economic costs, it is important to identify policies that can help prevent and fight against grand corruption. While bureaucratic corruption can normally be controlled through auditing, legislation, and institutional arrangements, the degenerative effects of political corruption cannot be counteracted by an administrative approach alone. Political corruption, however, calls for a different approach, i.e. one that empowers external watchdogs to keep an eye on politicians and their decisions. Policies that foster transparency can help promote this as they reduce the problem of information asymmetry by shedding light on the extent to which the government is pursuing the goals that are in the interest of its citizens. In other words, transparency not only enables citizens to evaluate to what extent their interests are being served by the government, it also encourages accountability and helps prevent abuses and misdeeds by officials .  

##Strategies against grand corruption
As the first global legally-binding international anti-corruption instrument, the United Nations Convention against Corruption (UNCAC) includes the following strategies as potential weapons to fight against grand corruption:  

* Conflict of Interest regulation: According to UNCAC, it is crucial for states to take measures to prevent conflicts of interests and to guarantee the integrity and impartiality of the public officials involved in decision-making processes, as they should not be able to take advantage of their position for their own private gain. In the context of public procurement, for example, conflicts of interest arise if a public procurement official has an economic interest in one of the bidding companies or is offered a future employment in one of them [@heggstad2010].  
* Financial disclosure of assets of relevant government officials is also a good practice to promote integrity in the public sector. Ideally, public officials and politicians should regularly declare their income, assets, liabilities, gifts and benefits, as well as unpaid employments and contracts, participation in organisations and post-tenure positions. This information is particularly important to detect cases of illicit enrichment, embezzlement, etc.  

##Research Question and Methodology
The proposed research aims at giving a comparative overview of the state of grand corruption across the EU28 and measure the impact of different transparency mechanisms on the levels of grand corruption in the region. The research question can thus be summarized as follows: Are the transparency and accountability policies proposed by UNCAC effective in preventing and curbing grand corruption in the EU28?     
It is necessary to mention, however, that assuming that these policies can, by themselves, eradicate or curb corruption on their own is not realistic given the complexity of the issue. This research will therefore part from the assumption that transparency mechanisms can only be effective when they interact with other factors that guarantee that they can be effectively implemented, such as a strong and independent judiciary. Another important component for these transparency initiatives to work is to have engaged and informed citizens with enough knowledge to be able to demand accountability from their government. The main hypothesis for this paper is therefore that conflict of interest regulation and financial disclosure mechanisms will only affect grand corruption in in the presence of other intervening variables such as an independent judiciary, a free media and an engaged body of citizens. We will use diverse statistical methods to test this hypothesis, including some cross-sectional and time series models to consider the time factor and check whether the UNCAC suggested policies start being effective with some lag after they are enacted.  

#Data Sources
The World Economic Forum???s (WEF) Global Competitiveness Report (GCR) aggregates governance, macroeconomic and the business aspects of competitiveness into a single index in order to assess a county??s productivity and prosperity. Some of the data included in the GCR comes directly from an expert survey conducted by the WEF among 13,500 firms inquiring about practices associated to grand corruption, such as deviation of public funds, lack of transparency in government policy-making, etc. This will therefore be source of our dependent variables. The GCR covers a total of 144 countries in all regions of the world for the period 2004-2016.  

The operationalization of our transparency policy variables will be derived from the World Bank???s Public Accountability Mechanisms (PAM) database. This data source provides information about relevant legislation, political events, and notable incidents of corruption 35 European countries across. It also summarizes specific indicators related to the accountability mechanisms of income and asset disclosure, freedom of information, conflict of interest, immunity protections, and ethics training. The PAM database will therefore be the basis for the construction of our transparency variables. Its limited geographical coverage, however, will limit our analysis to the EU28 only.  

The QoG Institute offers a range of datasets on indicators of Quality of Government and other related indicators. This database will be used to obtain information on civil society, the judicial system in the countries, etc. Finally, Eurostat data will also be used to retrieve the necessary economic control variables for our models.  

# References
